# Understanding Pandas Series and DataFrames - Lab

# Introduction

In this lab, let's get some hands on practice working with data cleanup using Pandas.

## Objectives
You will be able to:

* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
df = pd.read_csv('turnstile_180901.txt')
print(len(df))
df.head()

197625

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

# Practice

## Objectives
You will be able to:
* Understand and explain what Pandas Series and DataFrames are and how they differ from dictionaries and lists
* Create Series & DataFrames from dictionaries and lists
* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

# Rename all the columns to lower case

In [9]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

In [10]:
df.columns = [x.lower() for x in df.columns]
df.head()

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

# Change the Index to be the Line Names

In [5]:
#save this for later, since I cheated and looked ahead
temp = df.index
df.index = df.linename
df.head()
#that didn't work b/c I ran the cells out of order and over-wrote temp

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits
linename,,,,,,,,,,,
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
NQR456W,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

In [11]:
df.reset_index()
df.head()

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

# Painstakingly change the index back

In [51]:
df.index = range(1,len(df)+1)
df.loc[:,['station', 'linename']]

              station linename
1               59 ST  NQR456W
2               59 ST  NQR456W
3               59 ST  NQR456W
4               59 ST  NQR456W
5               59 ST  NQR456W
6               59 ST  NQR456W
7               59 ST  NQR456W
8               59 ST  NQR456W
9               59 ST  NQR456W
10              59 ST  NQR456W
11              59 ST  NQR456W
12              59 ST  NQR456W
13              59 ST  NQR456W
14              59 ST  NQR456W
15              59 ST  NQR456W
16              59 ST  NQR456W
17              59 ST  NQR456W
18              59 ST  NQR456W
19              59 ST  NQR456W
20              59 ST  NQR456W
21              59 ST  NQR456W
22              59 ST  NQR456W
23              59 ST  NQR456W
24              59 ST  NQR456W
25              59 ST  NQR456W
26              59 ST  NQR456W
27              59 ST  NQR456W
28              59 ST  NQR456W
29              59 ST  NQR456W
30              59 ST  NQR456W
...               ...      ...
197596  RIT-ROOSEVELT        R
197597  RIT-ROOSEVELT        R
197598  RIT-ROOSEVELT        R
197599  RIT-ROOSEVELT        R
197600  RIT-ROOSEVELT        R
197601  RIT-ROOSEVELT        R
197602  RIT-ROOSEVELT        R
197603  RIT-ROOSEVELT        R
197604  RIT-ROOSEVELT        R
197605  RIT-ROOSEVELT        R
197606  RIT-ROOSEVELT        R
197607  RIT-ROOSEVELT        R
197608  RIT-ROOSEVELT        R
197609  RIT-ROOSEVELT        R
197610  RIT-ROOSEVELT        R
197611  RIT-ROOSEVELT        R
197612  RIT-ROOSEVELT        R
197613  RIT-ROOSEVELT        R
197614  RIT-ROOSEVELT        R
197615  RIT-ROOSEVELT        R
197616  RIT-ROOSEVELT        R
197617  RIT-ROOSEVELT        R
197618  RIT-ROOSEVELT        R
197619  RIT-ROOSEVELT        R
197620  RIT-ROOSEVELT        R
197621  RIT-ROOSEVELT        R
197622  RIT-ROOSEVELT        R
197623  RIT-ROOSEVELT        R
197624  RIT-ROOSEVELT        R
197625  RIT-ROOSEVELT        R

[197625 rows x 2 columns]

## Create another column 'Num_Lines' that is a count of how many lines pass through a station. Then sort your dataframe by this column in descending order.

In [6]:
df[['linename','station']]

KeyError: "['linename' 'station'] not in index"

In [77]:
stations = df.groupby('station').groups
print(stations.items())
num_lines_through_stations = {k:len(v) for k,v in stations.items()}
num_lines_through_stations['59 ST']

dict_items([('1 AV', Int64Index([30355, 30356, 30357, 30358, 30359, 30360, 30361, 30362, 30363,
            30364,
            ...
            30765, 30766, 30767, 30768, 30769, 30770, 30771, 30772, 30773,
            30774],
           dtype='int64', length=420)), ('103 ST', Int64Index([ 45570,  45571,  45572,  45573,  45574,  45575,  45576,  45577,
             45578,  45579,
            ...
            157992, 157993, 157994, 157995, 157996, 157997, 157998, 157999,
            158000, 158001],
           dtype='int64', length=661)), ('103 ST-CORONA', Int64Index([181220, 181221, 181222, 181223, 181224, 181225, 181226, 181227,
            181228, 181229,
            ...
            181606, 181607, 181608, 181609, 181610, 181611, 181612, 181613,
            181614, 181615],
           dtype='int64', length=396)), ('104 ST', Int64Index([39541, 39542, 39543, 39544, 39545, 39546, 39547, 39548, 39549,
            39550,
            ...
            65777, 65778, 65779, 65780, 65781, 65782, 65783, 65784, 65785,
            65786],
           dtype='int64', length=373)), ('110 ST', Int64Index([158002, 158003, 158004, 158005, 158006, 158007, 158008, 158009,
            158010, 158011,
            ...
            158244, 158245, 158246, 158247, 158248, 158249, 158250, 158251,
            158252, 158253],
           dtype='int64', length=252)), ('111 ST', Int64Index([ 39709,  39710,  39711,  39712,  39713,  39714,  39715,  39716,
             39717,  39718,
            ...
            181831, 181832, 181833, 181834, 181835, 181836, 181837, 181838,
            181839, 181840],
           dtype='int64', length=687)), ('116 ST', Int64Index([ 45303,  45304,  45305,  45306,  45307,  45308,  45309,  45310,
             45311,  45312,
            ...
            163316, 163317, 163318, 163319, 163320, 163321, 163322, 163323,
            163324, 163325],
           dtype='int64', length=939)), ('116 ST-COLUMBIA', Int64Index([138501, 138502, 138503, 138504, 138505, 138506, 138507, 138508,
            138509, 138510,
            ...
            138749, 138750, 138751, 138752, 138753, 138754, 138755, 138756,
            138757, 138758],
           dtype='int64', length=258)), ('121 ST', Int64Index([39877, 39878, 39879, 39880, 39881, 39882, 39883, 39884, 39885,
            39886,
            ...
            40077, 40078, 40079, 40080, 40081, 40082, 40083, 40084, 40085,
            40086],
           dtype='int64', length=210)), ('125 ST', Int64Index([ 44599,  44600,  44601,  44602,  44603,  44604,  44605,  44606,
             44607,  44608,
            ...
            163652, 163653, 163654, 163655, 163656, 163657, 163658, 163659,
            163660, 163661],
           dtype='int64', length=1852)), ('135 ST', Int64Index([ 44134,  44135,  44136,  44137,  44138,  44139,  44140,  44141,
             44142,  44143,
            ...
            164171, 164172, 164173, 164174, 164175, 164176, 164177, 164178,
            164179, 164180],
           dtype='int64', length=984)), ('137 ST CITY COL', Int64Index([138969, 138970, 138971, 138972, 138973, 138974, 138975, 138976,
            138977, 138978,
            ...
            139384, 139385, 139386, 139387, 139388, 139389, 139390, 139391,
            139392, 139393],
           dtype='int64', length=425)), ('138/GRAND CONC', Int64Index([159192, 159193, 159194, 159195, 159196, 159197, 159198, 159199,
            159200, 159201,
            ...
            159311, 159312, 159313, 159314, 159315, 159316, 159317, 159318,
            159319, 159320],
           dtype='int64', length=129)), ('14 ST', Int64Index([ 53459,  53460,  53461,  53462,  53463,  53464,  53465,  53466,
             53467,  53468,
            ...
            128166, 128167, 128168, 128169, 128170, 128171, 128172, 128173,
            128174, 128175],
           dtype='int64', length=1803)), ('14 ST-UNION SQ', Int64Index([  4571,   4572,   4573,   4574,   4575,   4576,   4577,   4578,
              4579,   4580,
            ...
            148224, 148225, 148226, 148227, 148228, 148229, 148230, 148231,
            148232, 148233],
           dtype='int64', length=1604)), ('145 ST', Int64Index([ 43756,  43757,  43758,  43759,  43760,  43761,  43762,  43763,
             43764,  43765,
            ...
            139674, 139675, 139676, 139677, 139678, 139679, 139680, 139681,
            139682, 139683],
           dtype='int64', length=668)), ('149/GRAND CONC', Int64Index([159321, 159322, 159323, 159324, 159325, 159326, 159327, 159328,
            159329, 159330,
            ...
            159605, 159606, 159607, 159608, 159609, 159610, 159611, 159612,
            159613, 159614],
           dtype='int64', length=294)), ('14TH STREET', Int64Index([115343, 115344, 115345, 115346, 115347, 115348, 115349, 115350,
            115351, 115352,
            ...
            115773, 115774, 115775, 115776, 115777, 115778, 115779, 115780,
            115781, 115782],
           dtype='int64', length=440)), ('15 ST-PROSPECT', Int64Index([100832, 100833, 100834, 100835, 100836, 100837, 100838, 100839,
            100840, 100841,
            ...
            101344, 101345, 101346, 101347, 101348, 101349, 101350, 101351,
            101352, 101353],
           dtype='int64', length=522)), ('155 ST', Int64Index([43547, 43548, 43549, 43550, 43551, 43552, 43553, 43554, 43555,
            43556,
            ...
            69738, 69739, 69740, 69741, 69742, 69743, 69744, 69745, 69746,
            69747],
           dtype='int64', length=335)), ('157 ST', Int64Index([139684, 139685, 139686, 139687, 139688, 139689, 139690, 139691,
            139692, 139693,
            ...
            140010, 140011, 140012, 140013, 140014, 140015, 140016, 140017,
            140018, 140019],
           dtype='int64', length=336)), ('161/YANKEE STAD', Int64Index([ 69748,  69749,  69750,  69751,  69752,  69753,  69754,  69755,
             69756,  69757,
            ...
            160452, 160453, 160454, 160455, 160456, 160457, 160458, 160459,
            160460, 160461],
           dtype='int64', length=1587)), ('167 ST', Int64Index([ 70488,  70489,  70490,  70491,  70492,  70493,  70494,  70495,
             70496,  70497,
            ...
            160620, 160621, 160622, 160623, 160624, 160625, 160626, 160627,
            160628, 160629],
           dtype='int64', length=228)), ('168 ST', Int64Index([ 43002,  43003,  43004,  43005,  43006,  43007,  43008,  43009,
             43010,  43011,
            ...
            140304, 140305, 140306, 140307, 140308, 140309, 140310, 140311,
            140312, 140313],
           dtype='int64', length=839)), ('169 ST', Int64Index([85968, 85969, 85970, 85971, 85972, 85973, 85974, 85975, 85976,
            85977,
            ...
            86596, 86597, 86598, 86599, 86600, 86601, 86602, 86603, 86604,
            86605],
           dtype='int64', length=638)), ('170 ST', Int64Index([ 70548,  70549,  70550,  70551,  70552,  70553,  70554,  70555,
             70556,  70557,
            ...
            160793, 160794, 160795, 160796, 160797, 160798, 160799, 160800,
            160801, 160802],
           dtype='int64', length=593)), ('174 ST', Int64Index([166510, 166511, 166512, 166513, 166514, 166515, 166516, 166517,
            166518, 166519,
            ...
            166758, 166759, 166760, 166761, 166762, 166763, 166764, 166765,
            166766, 166767],
           dtype='int64', length=258)), ('175 ST', Int64Index([42330, 42331, 42332, 42333, 42334, 42335, 42336, 42337, 42338,
            42339,
            ...
            42992, 42993, 42994, 42995, 42996, 42997, 42998, 42999, 43000,
            43001],
           dtype='int64', length=672)), ('176 ST', Int64Index([160971, 160972, 160973, 160974, 160975, 160976, 160977, 160978,
            160979, 160980,
            ...
            161129, 161130, 161131, 161132, 161133, 161134, 161135, 161136,
            161137, 161138],
           dtype='int64', length=168)), ('18 AV', Int64Index([ 25244,  25245,  25246,  25247,  25248,  25249,  25250,  25251,
             25252,  25253,
            ...
            102898, 102899, 102900, 102901, 102902, 102903, 102904, 102905,
            102906, 102907],
           dtype='int64', length=588)), ('18 ST', Int64Index([128176, 128177, 128178, 128179, 128180, 128181, 128182, 128183,
            128184, 128185,
            ...
            128499, 128500, 128501, 128502, 128503, 128504, 128505, 128506,
            128507, 128508],
           dtype='int64', length=333)), ('181 ST', Int64Index([ 42066,  42067,  42068,  42069,  42070,  42071,  42072,  42073,
             42074,  42075,
            ...
            140519, 140520, 140521, 140522, 140523, 140524, 140525, 140526,
            140527, 140528],
           dtype='int64', length=479)), ('182-183 STS', Int64Index([71427, 71428, 71429, 71430, 71431, 71432, 71433, 71434, 71435,
            71436,
            ...
            71540, 71541, 71542, 71543, 71544, 71545, 71546, 71547, 71548,
            71549],
           dtype='int64', length=123)), ('183 ST', Int64Index([161354, 161355, 161356, 161357, 161358, 161359, 161360, 161361,
            161362, 161363,
            ...
            161508, 161509, 161510, 161511, 161512, 161513, 161514, 161515,
            161516, 161517],
           dtype='int64', length=164)), ('190 ST', Int64Index([41940, 41941, 41942, 41943, 41944, 41945, 41946, 41947, 41948,
            41949,
            ...
            42056, 42057, 42058, 42059, 42060, 42061, 42062, 42063, 42064,
            42065],
           dtype='int64', length=126)), ('191 ST', Int64Index([140529, 140530, 140531, 140532, 140533, 140534, 140535, 140536,
            140537, 140538,
            ...
            140687, 140688, 140689, 140690, 140691, 140692, 140693, 140694,
            140695, 140696],
           dtype='int64', length=168)), ('2 AV', Int64Index([97553, 97554, 97555, 97556, 97557, 97558, 97559, 97560, 97561,
            97562,
            ...
            97967, 97968, 97969, 97970, 97971, 97972, 97973, 97974, 97975,
            97976],
           dtype='int64', length=424)), ('20 AV', Int64Index([25412, 25413, 25414, 25415, 25416, 25417, 25418, 25419, 25420,
            25421,
            ...
            27578, 27579, 27580, 27581, 27582, 27583, 27584, 27585, 27586,
            27587],
           dtype='int64', length=251)), ('207 ST', Int64Index([140949, 140950, 140951, 140952, 140953, 140954, 140955, 140956,
            140957, 140958,
            ...
            141191, 141192, 141193, 141194, 141195, 141196, 141197, 141198,
            141199, 141200],
           dtype='int64', length=252)), ('21 ST', Int64Index([88366, 88367, 88368, 88369, 88370, 88371, 88372, 88373, 88374,
            88375,
            ...
            88482, 88483, 88484, 88485, 88486, 88487, 88488, 88489, 88490,
            88491],
           dtype='int64', length=126)), ('21 ST-QNSBRIDGE', Int64Index([105524, 105525, 105526, 105527, 105528, 105529, 105530, 105531,
            105532, 105533,
            ...
            105766, 105767, 105768, 105769, 105770, 105771, 105772, 105773,
            105774, 105775],
           dtype='int64', length=252)), ('215 ST', Int64Index([141201, 141202, 141203, 141204, 141205, 141206, 141207, 141208,
            141209, 141210,
            ...
            141359, 141360, 141361, 141362, 141363, 141364, 141365, 141366,
            141367, 141368],
           dtype='int64', length=168)), ('219 ST', Int64Index([168397, 168398, 168399, 168400, 168401, 168402, 168403, 168404,
            168405, 168406,
            ...
            168519, 168520, 168521, 168522, 168523, 168524, 168525, 168526,
            168527, 168528],
           dtype='int64', length=132)), ('225 ST', Int64Index([168529, 168530, 168531, 168532, 168533, 168534, 168535, 168536,
            168537, 168538,
            ...
            168645, 168646, 168647, 168648, 168649, 168650, 168651, 168652,
            168653, 168654],
           dtype='int64', length=126)), ('23 ST', Int64Index([  3977,   3978,   3979,   3980,   3981,   3982,   3983,   3984,
              3985,   3986,
            ...
            149301, 149302, 149303, 149304, 149305, 149306, 149307, 149308,
            149309, 149310],
           dtype='int64', length=2605)), ('231 ST', Int64Index([141579, 141580, 141581, 141582, 141583, 141584, 141585, 141586,
            141587, 141588,
            ...
            141989, 141990, 141991, 141992, 141993, 141994, 141995, 141996,
            141997, 141998],
           dtype='int64', length=420)), ('233 ST', Int64Index([168655, 168656, 168657, 168658, 168659, 168660, 168661, 168662,
            168663, 168664,
            ...
            168855, 168856, 168857, 168858, 168859, 168860, 168861, 168862,
            168863, 168864],
           dtype='int64', length=210)), ('238 ST', Int64Index([141999, 142000, 142001, 142002, 142003, 142004, 142005, 142006,
            142007, 142008,
            ...
            142147, 142148, 142149, 142150, 142151, 142152, 142153, 142154,
            142155, 142156],
           dtype='int64', length=158)), ('25 AV', Int64Index([27889, 27890, 27891, 27892, 27893, 27894, 27895, 27896, 27897,
            27898,
            ...
            28020, 28021, 28022, 28023, 28024, 28025, 28026, 28027, 28028,
            28029],
           dtype='int64', length=141)), ('25 ST', Int64Index([22025, 22026, 22027, 22028, 22029, 22030, 22031, 22032, 22033,
            22034,
            ...
            22270, 22271, 22272, 22273, 22274, 22275, 22276, 22277, 22278,
            22279],
           dtype='int64', length=255)), ('28 ST', Int64Index([  3595,   3596,   3597,   3598,   3599,   3600,   3601,   3602,
              3603,   3604,
            ...
            129255, 129256, 129257, 129258, 129259, 129260, 129261, 129262,
            129263, 129264],
           dtype='int64', length=844)), ('3 AV', Int64Index([30103, 30104, 30105, 30106, 30107, 30108, 30109, 30110, 30111,
            30112,
            ...
            30345, 30346, 30347, 30348, 30349, 30350, 30351, 30352, 30353,
            30354],
           dtype='int64', length=252)), ('3 AV 138 ST', Int64Index([169201, 169202, 169203, 169204, 169205, 169206, 169207, 169208,
            169209, 169210,
            ...
            169363, 169364, 169365, 169366, 169367, 169368, 169369, 169370,
            169371, 169372],
           dtype='int64', length=172)), ('3 AV-149 ST', Int64Index([164307, 164308, 164309, 164310, 164311, 164312, 164313, 164314,
            164315, 164316,
            ...
            165200, 165201, 165202, 165203, 165204, 165205, 165206, 165207,
            165208, 165209],
           dtype='int64', length=903)), ('30 AV', Int64Index([176404, 176405, 176406, 176407, 176408, 176409, 176410, 176411,
            176412, 176413,
            ...
            176709, 176710, 176711, 176712, 176713, 176714, 176715, 176716,
            176717, 176718],
           dtype='int64', length=315)), ('33 ST', Int64Index([149311, 149312, 149313, 149314, 149315, 149316, 149317, 149318,
            149319, 149320,
            ...
            150225, 150226, 150227, 150228, 150229, 150230, 150231, 150232,
            150233, 150234],
           dtype='int64', length=924)), ('33 ST-RAWSON ST', Int64Index([177362, 177363, 177364, 177365, 177366, 177367, 177368, 177369,
            177370, 177371,
            ...
            177772, 177773, 177774, 177775, 177776, 177777, 177778, 177779,
            177780, 177781],
           dtype='int64', length=420)), ('34 ST-HERALD SQ', Int64Index([ 2966,  2967,  2968,  2969,  2970,  2971,  2972,  2973,  2974,
             2975,
            ...
            95602, 95603, 95604, 95605, 95606, 95607, 95608, 95609, 95610,
            95611],
           dtype='int64', length=2311)), ('34 ST-HUDSON YD', Int64Index([184587, 184588, 184589, 184590, 184591, 184592, 184593, 184594,
            184595, 184596,
            ...
            185837, 185838, 185839, 185840, 185841, 185842, 185843, 185844,
            185845, 185846],
           dtype='int64', length=1260)), ('34 ST-PENN STA', Int64Index([ 50420,  50421,  50422,  50423,  50424,  50425,  50426,  50427,
             50428,  50429,
            ...
            130875, 130876, 130877, 130878, 130879, 130880, 130881, 130882,
            130883, 130884],
           dtype='int64', length=4019)), ('36 AV', Int64Index([176152, 176153, 176154, 176155, 176156, 176157, 176158, 176159,
            176160, 176161,
            ...
            176394, 176395, 176396, 176397, 176398, 176399, 176400, 176401,
            176402, 176403],
           dtype='int64', length=252)), ('36 ST', Int64Index([22280, 22281, 22282, 22283, 22284, 22285, 22286, 22287, 22288,
            22289,
            ...
            77399, 77400, 77401, 77402, 77403, 77404, 77405, 77406, 77407,
            77408],
           dtype='int64', length=684)), ('4 AV-9 ST', Int64Index([100335, 100336, 100337, 100338, 100339, 100340, 100341, 100342,
            100343, 100344,
            ...
            100493, 100494, 100495, 100496, 100497, 100498, 100499, 100500,
            100501, 100502],
           dtype='int64', length=168)), ('40 ST LOWERY ST', Int64Index([177782, 177783, 177784, 177785, 177786, 177787, 177788, 177789,
            177790, 177791,
            ...
            178024, 178025, 178026, 178027, 178028, 178029, 178030, 178031,
            178032, 178033],
           dtype='int64', length=252)), ('42 ST-BRYANT PK', Int64Index([93050, 93051, 93052, 93053, 93054, 93055, 93056, 93057, 93058,
            93059,
            ...
            93920, 93921, 93922, 93923, 93924, 93925, 93926, 93927, 93928,
            93929],
           dtype='int64', length=880)), ('42 ST-PORT AUTH', Int64Index([48239, 48240, 48241, 48242, 48243, 48244, 48245, 48246, 48247,
            48248,
            ...
            50410, 50411, 50412, 50413, 50414, 50415, 50416, 50417, 50418,
            50419],
           dtype='int64', length=2181)), ('45 ST', Int64Index([22544, 22545, 22546, 22547, 22548, 22549, 22550, 22551, 22552,
            22553,
            ...
            22702, 22703, 22704, 22705, 22706, 22707, 22708, 22709, 22710,
            22711],
           dtype='int64', length=168)), ('46 ST', Int64Index([77787, 77788, 77789, 77790, 77791, 77792, 77793, 77794, 77795,
            77796,
            ...
            78404, 78405, 78406, 78407, 78408, 78409, 78410, 78411, 78412,
            78413],
           dtype='int64', length=627)), ('46 ST BLISS ST', Int64Index([178034, 178035, 178036, 178037, 178038, 178039, 178040, 178041,
            178042, 178043,
            ...
            178552, 178553, 178554, 178555, 178556, 178557, 178558, 178559,
            178560, 178561],
           dtype='int64', length=528)), ('47-50 STS ROCK', Int64Index([91434, 91435, 91436, 91437, 91438, 91439, 91440, 91441, 91442,
            91443,
            ...
            93040, 93041, 93042, 93043, 93044, 93045, 93046, 93047, 93048,
            93049],
           dtype='int64', length=1616)), ('49 ST', Int64Index([1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694,
            ...
            2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613],
           dtype='int64', length=929)), ('4AV-9 ST', Int64Index([21265, 21266, 21267, 21268, 21269, 21270, 21271, 21272, 21273,
            21274,
            ...
            21717, 21718, 21719, 21720, 21721, 21722, 21723, 21724, 21725,
            21726],
           dtype='int64', length=462)), ('5 AV/53 ST', Int64Index([73532, 73533, 73534, 73535, 73536, 73537, 73538, 73539, 73540,
            73541,
            ...
            74446, 74447, 74448, 74449, 74450, 74451, 74452, 74453, 74454,
            74455],
           dtype='int64', length=924)), ('5 AV/59 ST', Int64Index([ 505,  506,  507,  508,  509,  510,  511,  512,  513,  514,
            ...
            1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100],

2229

In [78]:
#df['Num_Lines'] = num_lines_through_stations[df['station']]
#df['station'][10:30]
#len(stations[df['station'][10]])
df['Num_Lines'] = df['linename'].map(lambda x:len(x))
df.tail(600)

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits,Num_Lines
197026,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/30/2018,00:00:00,REGULAR,864,0,1
197027,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/30/2018,04:00:00,REGULAR,864,0,1
197028,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/30/2018,08:00:00,REGULAR,864,0,1
197029,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/30/2018,12:00:00,REGULAR,864,0,1
197030,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/30/2018,16:00:00,REGULAR,864,0,1
197031,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/30/2018,20:00:00,REGULAR,864,0,1
197032,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/31/2018,00:00:00,REGULAR,865,0,1
197033,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/31/2018,04:00:00,REGULAR,865,0,1
197034,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/31/2018,08:00:00,REGULAR,865,0,1
197035,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/31/2018,12:00:00,REGULAR,865,0,1
197036,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/31/2018,16:00:00,REGULAR,865,0,1
197037,S101A,R070,01-05-00,ST. GEORGE,1,SRT,08/31/2018,20:00:00,REGULAR,865,0,1
197038,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/25/2018,00:00:00,REGULAR,559,0,1
197039,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/25/2018,04:00:00,REGULAR,559,0,1
197040,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/25/2018,08:00:00,REGULAR,559,0,1
197041,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/25/2018,12:00:00,REGULAR,559,0,1
197042,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/25/2018,16:00:00,REGULAR,559,0,1
197043,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/25/2018,20:00:00,REGULAR,559,0,1
197044,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/26/2018,00:00:00,REGULAR,559,0,1
197045,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/26/2018,04:00:00,REGULAR,559,0,1
197046,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/26/2018,08:00:00,REGULAR,559,0,1
197047,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/26/2018,12:00:00,REGULAR,560,0,1
197048,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/26/2018,16:00:00,REGULAR,560,0,1
197049,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/26/2018,20:00:00,REGULAR,560,0,1
197050,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/27/2018,00:00:00,REGULAR,560,0,1
197051,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/27/2018,04:00:00,REGULAR,560,0,1
197052,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/27/2018,08:00:00,REGULAR,560,0,1
197053,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/27/2018,12:00:00,REGULAR,560,0,1
197054,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/27/2018,16:00:00,REGULAR,560,0,1
197055,S101A,R070,01-05-01,ST. GEORGE,1,SRT,08/27/2018,20:00:00,REGULAR,560,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
197596,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348,1
197597,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348,1
197598,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348,1
197599,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348,1
197600,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348,1
197601,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348,1
197602,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348,1
197603,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348,1
197604,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348,1
197605,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348,1
197606,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348,1
197607,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348,1
197608,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348,1
197609,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348,1
197610,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348,1
197611,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348,1
197612,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348,1
197613,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348,1
197614,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348,1
197615,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348,1
197616,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348,1
197617,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348,1
197618,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348,1
197619,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348,1
197620,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348,1
197621,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348,1
197622,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348,1
197623,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348,1
197624,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348,1
197625,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348,1

## Write a function to clean a column name.

In [ ]:
def clean(col_name):
    cleaned = #Your code here; whatever you want to do to col_name. Hint: think back to str methods.
    return cleaned

In [ ]:
#This is a list comprehension. It applies your clean function to every item in the list.
#We then reassign that to df.columns
#You shouldn't have to change anything here.
#Your function above should work appropriately here.
df.columns = [clean(col) for col in df.columns]

In [ ]:
#Checking the output, we can see the results.
df.columns

## Compare subway traffic by day of the week. Display this as a graph.

In [ ]:
#Your code here

## Is there more subway traffic on a weekend or a weekday?    Be specific in comparing magnitudes.

In [ ]:
#Your code here

# Drop a couple of columns

In [ ]:
# Your code here